// src/config.js

const config = {
  API_URL_SECRET: import.meta.env.VITE_API_URL_SECRET,
  API_KEY_SECRET: import.meta.env.VITE_API_KEY_SECRET,
  TOKEN_KEY_SECRET: import.meta.env.VITE_TOKEN_KEY_SECRET,
  MDX_PROFILEID_SECRET: import.meta.env.VITE_MDX_PROFILEID_SECRET,
  CART_KEY_SECRET: import.meta.env.VITE_CART_KEY_SECRET,
  GEST_ADDRES_SECRET: import.meta.env.VITE_GEST_ADDRES_SECRET,
  LANGUAGE_NETFLIX_SECRET: import.meta.env.VITE_LANGUAGE_NETFLIX_SECRET,
  CLIENT_ID_SECRET: import.meta.env.VITE_CLIENT_ID_SECRET,
  LOGIN_ROUTE_SECRET: import.meta.env.VITE_LOGIN_ROUTE_SECRET,
  REGISTER_ROUTE_SECRET: import.meta.env.VITE_REGISTER_ROUTE_SECRET,
  CHECK_TOKEN_SECRET: import.meta.env.VITE_CHECK_TOKEN_SECRET,
  CHECK_MANAGER_SECRET: import.meta.env.VITE_CHECK_MANAGER_SECRET,
  CHECK_ADMIN_SECRET: import.meta.env.VITE_CHECK_ADMIN_SECRET,
  USER_INFO_ROUTE_SECRET: import.meta.env.VITE_USER_INFO_ROUTE_SECRET,
  USER_SCREENS_ROUTE_SECRET: import.meta.env.VITE_USER_SCREENS_ROUTE_SECRET,
  USER_ROUTE_SECRET: import.meta.env.VITE_USER_ROUTE_SECRET,
  USER_LIST_ROUTE_SECRET: import.meta.env.VITE_USER_LIST_ROUTE_SECRET,
  DELETE_USER_ROUTE_SECRET: import.meta.env.VITE_DELETE_USER_ROUTE_SECRET,
  CHANGE_ROLE_ROUTE_SECRET: import.meta.env.VITE_CHANGE_ROLE_ROUTE_SECRET,
  CATEGORIES_ROUT_SECRET: import.meta.env.VITE_CATEGORIES_ROUT_SECRET,
  PRODUCT_ROUT_SECRET: import.meta.env.VITE_PRODUCT_ROUT_SECRET,
};

export default config;
